# .travis.yml
language: go

sudo: false

go:
<<<<<<< HEAD
  - "1.9"
  - "1.10"
  - "1.11"
=======
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - tip
>>>>>>> new-feature

script:
  - ./.travis.gofmt.sh
  - go test -v -race $(go list ./... | grep -v vendor)
